"""
DCPP Interoperability Test Suite

This module contains test cases for validating interoperability between
Python and Rust implementations of the DCPP wire protocol.

Test Categories:
1. Wire Format Tests - Validate framing profiles produce identical bytes
2. CBOR Serialization Tests - Validate message serialization compatibility
3. Signature Tests - Validate Ed25519 signature compatibility
4. CRC32C Tests - Validate checksum computation compatibility
5. Test Vectors - Known-good message bytes for cross-implementation testing
6. Protocol Compliance Tests - Validate RFC requirements
7. Edge Cases - Boundary conditions and error handling

Usage:
    These tests can be run against test vectors generated by the Rust
    implementation to ensure byte-for-byte compatibility.

    To generate test vectors from Rust:
        cargo run --bin generate_test_vectors > test_vectors.json

    To run interop tests:
        pytest tests/e2e/test_interop.py -v
"""

from __future__ import annotations

import hashlib
import json
import os
import struct
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import cbor2
import pytest

from dcpp_python.core.constants import (
    MAGIC_BYTES,
    MAX_MESSAGE_SIZE,
    MessageType,
    ErrorCode,
    Capability,
    AccessMode,
    CollectionType,
    StorageType,
    ItemStatus,
)
from dcpp_python.framing import Profile1Framer, FramingError, ChecksumError
from dcpp_python.messages import (
    Hello,
    Announce,
    CollectionAnnouncement,
    GetManifest,
    ManifestResponse,
    GetPeers,
    PeersResponse,
    PeerInfo,
    HealthProbe,
    HealthResponse,
    Challenge,
    ChallengeResponse,
    Goodbye,
    ErrorResponse,
    decode_message,
)
from dcpp_python.manifest import (
    Manifest,
    Item,
    TorrentInfo,
    EncryptionConfig,
)


def ensure_test_vectors(path: Path) -> None:
    """
    Ensure Rust-generated test vectors exist for interop tests.

    These vectors are required for byte-for-byte compatibility checks.
    """
    if path.exists():
        return

    repo_root = Path(__file__).resolve().parents[2]
    print("[SETUP] Generating test vectors via cargo run --bin generate_test_vectors")
    with path.open("w", encoding="utf-8") as f:
        result = subprocess.run(
            ["cargo", "run", "--bin", "generate_test_vectors"],
            cwd=repo_root,
            stdout=f,
            stderr=subprocess.PIPE,
            text=True,
            timeout=300,
        )
    if result.returncode != 0:
        raise RuntimeError(
            "Failed to generate test vectors:\n"
            f"{result.stderr}"
        )
from dcpp_python.utils import crc32c


# =============================================================================
# Test Vector Definitions
# =============================================================================

@dataclass
class TestVector:
    """A test vector for cross-implementation validation."""
    __test__ = False
    name: str
    message_type: MessageType
    payload_dict: dict[str, Any]
    expected_cbor_hex: str | None = None  # Expected CBOR bytes (hex)
    expected_profile1_hex: str | None = None  # Expected Profile 1 frame (hex)


# Canonical test vectors with known-good byte representations
# These should produce identical bytes in both Rust and Python implementations
TEST_VECTORS = [
    # Minimal HELLO message
    TestVector(
        name="hello_minimal",
        message_type=MessageType.HELLO,
        payload_dict={
            "node_id": bytes([0x01, 0x02, 0x03, 0x04]),
            "capabilities": [],
            "collections": [],
            "timestamp": 1704067200,  # 2024-01-01 00:00:00 UTC
        },
    ),
    # HELLO with all fields
    TestVector(
        name="hello_full",
        message_type=MessageType.HELLO,
        payload_dict={
            "node_id": bytes([0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]),
            "capabilities": ["guardian", "seeder", "private"],
            "collections": ["eth:0xBC4CA0", "polygon:0x123456"],
            "timestamp": 1704067200,
            "user_agent": "dcpp-test/1.0",
        },
    ),
    # GET_MANIFEST (simple request)
    TestVector(
        name="get_manifest_latest",
        message_type=MessageType.GET_MANIFEST,
        payload_dict={
            "collection_id": "eth:0xBC4CA0EdBa4FdB7e6944C6Ef82a61dD0f41B09",
        },
    ),
    # GET_MANIFEST with version
    TestVector(
        name="get_manifest_version",
        message_type=MessageType.GET_MANIFEST,
        payload_dict={
            "collection_id": "eth:0xBC4CA0",
            "version": 5,
        },
    ),
    # GET_MANIFEST with since_version (diff request)
    TestVector(
        name="get_manifest_diff",
        message_type=MessageType.GET_MANIFEST,
        payload_dict={
            "collection_id": "eth:0xBC4CA0",
            "since_version": 3,
        },
    ),
    # GET_PEERS (basic)
    TestVector(
        name="get_peers_basic",
        message_type=MessageType.GET_PEERS,
        payload_dict={
            "collection_id": "eth:0xBC4CA0",
            "max_peers": 20,
        },
    ),
    # GET_PEERS with shard
    TestVector(
        name="get_peers_shard",
        message_type=MessageType.GET_PEERS,
        payload_dict={
            "collection_id": "eth:0xBC4CA0",
            "shard_id": 5,
            "max_peers": 50,
        },
    ),
    # GOODBYE shutdown
    TestVector(
        name="goodbye_shutdown",
        message_type=MessageType.GOODBYE,
        payload_dict={
            "reason": "shutdown",
        },
    ),
    # GOODBYE leaving collections
    TestVector(
        name="goodbye_leaving",
        message_type=MessageType.GOODBYE,
        payload_dict={
            "reason": "leaving_collection",
            "collections": ["eth:0xBC4CA0", "eth:0xDEADBEEF"],
        },
    ),
    # ERROR response
    TestVector(
        name="error_unknown_collection",
        message_type=MessageType.ERROR,
        payload_dict={
            "code": 1,  # UNKNOWN_COLLECTION
            "message": "Collection not found",
            "request_type": 0x0003,  # GET_MANIFEST
        },
    ),
    # HEALTH_PROBE
    TestVector(
        name="health_probe",
        message_type=MessageType.HEALTH_PROBE,
        payload_dict={
            "collection_id": "eth:0xBC4CA0",
            "challenges": [
                {"cid": "QmTestCid1", "offset": 0, "length": 256},
                {"cid": "QmTestCid2", "offset": 1024, "length": 512},
            ],
            "nonce": bytes([0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                           0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F]),
        },
    ),
    # HEALTH_RESPONSE
    TestVector(
        name="health_response",
        message_type=MessageType.HEALTH_RESPONSE,
        payload_dict={
            "nonce": bytes([0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                           0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F]),
            "responses": [
                {"cid": "QmTestCid1", "data": bytes([0xDE, 0xAD, 0xBE, 0xEF])},
                {"cid": "QmTestCid2", "error": "Content not available"},
            ],
        },
    ),
]


# =============================================================================
# Profile 1 Framing Tests
# =============================================================================

class TestProfile1Interop:
    """Test Profile 1 framing interoperability."""

    def test_magic_bytes(self):
        """Magic bytes should be 0x44435050 ('DCPP')."""
        payload = b"\xa0"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        assert frame[:4] == b"DCPP"
        assert struct.unpack(">I", frame[:4])[0] == 0x44435050

    def test_version_bytes(self):
        """Version bytes (offset 4-5) should be 0x0100 for DCPP v1.0."""
        payload = b"\xa0"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        assert frame[4:6] == b"\x01\x00"

    def test_message_type_offset(self):
        """Message type should be at offset 6-7, big-endian."""
        for msg_type in MessageType:
            payload = b"\xa0"
            frame = Profile1Framer.encode(msg_type, payload)

            encoded_type = struct.unpack(">H", frame[6:8])[0]
            assert encoded_type == msg_type.value

    def test_length_offset(self):
        """Payload length should be at offset 12-15, 4-byte big-endian."""
        test_payloads = [b"", b"x", b"x" * 1000, b"x" * 100000]

        for payload in test_payloads:
            frame = Profile1Framer.encode(MessageType.MANIFEST, payload)

            length = struct.unpack(">I", frame[12:16])[0]
            assert length == len(payload)

    def test_crc32c_offset(self):
        """CRC32C should be at offset 16-19, big-endian."""
        payload = b"test payload for CRC"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        # Extract CRC from frame
        frame_crc = struct.unpack(">I", frame[16:20])[0]

        # Calculate expected CRC
        expected_crc = crc32c(payload)

        assert frame_crc == expected_crc

    def test_crc32c_known_vectors(self):
        """CRC32C should match known test vectors."""
        # CRC-32C (Castagnoli) test vectors
        test_vectors = [
            (b"", 0x00000000),
            (b"123456789", 0xE3069283),
            (b"The quick brown fox jumps over the lazy dog", 0x22620404),
        ]

        for data, expected in test_vectors:
            actual = crc32c(data)
            assert actual == expected, \
                f"CRC32C mismatch for {data!r}: expected {expected:#010x}, got {actual:#010x}"

    def test_header_size(self):
        """Profile 1 header should be exactly 20 bytes."""
        payload = b"test"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        # Header + payload
        assert len(frame) == 20 + len(payload)

    def test_crc_verification_failure(self):
        """Corrupted CRC should be detected."""
        payload = b"test payload"
        frame = bytearray(Profile1Framer.encode(MessageType.HELLO, payload))

        # Corrupt the CRC (at offset 16-19)
        frame[16] ^= 0xFF

        with pytest.raises(ChecksumError):
            Profile1Framer.decode(bytes(frame))

    def test_payload_corruption_detected(self):
        """Payload corruption should be detected via CRC."""
        payload = b"test payload"
        frame = bytearray(Profile1Framer.encode(MessageType.HELLO, payload))

        # Corrupt the payload (last byte)
        frame[-1] ^= 0xFF

        with pytest.raises(ChecksumError):
            Profile1Framer.decode(bytes(frame))


# =============================================================================
# CBOR Serialization Tests
# =============================================================================

class TestCBORInterop:
    """Test CBOR serialization compatibility."""

    def test_cbor_map_key_ordering(self):
        """CBOR maps should use consistent key ordering for signatures."""
        # This is critical for canonical CBOR (RFC 8949 Section 4.2.1)
        hello = Hello(
            version="1.0.0",
            node_id=b"\x01\x02\x03\x04",
            capabilities=["guardian"],
            collections=["eth:0x1234"],
            timestamp=1000,
            user_agent="test",
        )

        cbor_bytes = cbor2.dumps(hello.to_dict())
        decoded = cbor2.loads(cbor_bytes)

        # Keys should be preserved (including version)
        assert set(decoded.keys()) == {"version", "node_id", "capabilities", "collections", "timestamp", "user_agent"}

    def test_bytes_encoding(self):
        """Bytes should be encoded as CBOR byte strings (major type 2)."""
        data = {"node_id": b"\x01\x02\x03\x04"}
        cbor_bytes = cbor2.dumps(data)

        # Decode and verify type
        decoded = cbor2.loads(cbor_bytes)
        assert isinstance(decoded["node_id"], bytes)

    def test_integer_encoding_sizes(self):
        """Integers should use appropriate CBOR encoding sizes."""
        test_cases = [
            0,
            23,  # 1 byte (immediate)
            24,  # 2 bytes
            255,
            256,  # 3 bytes
            65535,
            65536,  # 5 bytes
            4294967295,
            4294967296,  # 9 bytes
        ]

        for value in test_cases:
            data = {"value": value}
            cbor_bytes = cbor2.dumps(data)
            decoded = cbor2.loads(cbor_bytes)
            assert decoded["value"] == value

    def test_float_encoding(self):
        """Float coverage values should serialize correctly."""
        test_cases = [0.0, 0.5, 1.0, 0.85, 0.999]

        for value in test_cases:
            data = {"coverage": value}
            cbor_bytes = cbor2.dumps(data)
            decoded = cbor2.loads(cbor_bytes)
            assert abs(decoded["coverage"] - value) < 0.0001

    def test_optional_fields_omission(self):
        """Optional fields set to None should be omitted from CBOR."""
        hello = Hello(
            version="1.0.0",
            node_id=b"\x01\x02\x03\x04",
            capabilities=[],
            collections=[],
            timestamp=1000,
            user_agent=None,  # Optional, should be omitted
        )

        hello_dict = hello.to_dict()
        assert "user_agent" not in hello_dict

    def test_nested_structures(self):
        """Nested CBOR structures should serialize correctly."""
        announce_collections = [
            CollectionAnnouncement(
                id="eth:0x1234",
                manifest_cid="QmTest",
                coverage=1.0,
                shard_ids=[0, 1, 2],
            ),
        ]

        for coll in announce_collections:
            cbor_bytes = cbor2.dumps(coll.to_dict())
            decoded = cbor2.loads(cbor_bytes)

            assert decoded["id"] == "eth:0x1234"
            assert decoded["shard_ids"] == [0, 1, 2]


# =============================================================================
# Message Roundtrip Tests
# =============================================================================

class TestMessageRoundtrip:
    """Test message serialization roundtrips."""

    @pytest.mark.parametrize("vector", TEST_VECTORS, ids=[v.name for v in TEST_VECTORS])
    def test_vector_roundtrip(self, vector: TestVector):
        """Test vectors should roundtrip correctly through encode/decode."""
        # Encode payload
        payload = cbor2.dumps(vector.payload_dict)

        frame = Profile1Framer.encode(vector.message_type, payload)
        decoded = Profile1Framer.decode(frame)
        assert decoded.message_type == vector.message_type
        assert cbor2.loads(decoded.payload) == vector.payload_dict

    def test_announce_with_signature_roundtrip(self):
        """ANNOUNCE with signature should preserve all fields."""
        from dcpp_python.crypto import generate_keypair, sign_message, derive_peer_id

        signing_key, verify_key = generate_keypair()
        node_id = derive_peer_id(verify_key)

        collections = [
            CollectionAnnouncement(
                id="eth:0x1234",
                manifest_cid="QmTest",
                coverage=1.0,
                shard_ids=[0, 1],
            ),
        ]

        timestamp = 1704067200
        expires_at = timestamp + 3600

        signable_dict = {
            "node_id": node_id,
            "announce_seq": timestamp,
            "collections": [c.to_dict() for c in collections],
            "timestamp": timestamp,
            "expires_at": expires_at,
        }

        signature = sign_message(signable_dict, signing_key)

        announce = Announce(
            node_id=node_id,
            announce_seq=timestamp,
            collections=collections,
            timestamp=timestamp,
            expires_at=expires_at,
            signature=signature,
        )

        # Roundtrip
        cbor_bytes = announce.to_cbor()
        restored = Announce.from_cbor(cbor_bytes)

        assert restored.node_id == node_id
        assert restored.signature == signature
        assert len(restored.collections) == 1
        assert restored.collections[0].id == "eth:0x1234"


# =============================================================================
# Cross-Implementation Test Vector Validation
# =============================================================================

class TestCrossImplementation:
    """
    Tests for validating against test vectors from other implementations.

    These tests read test vectors from a JSON file that can be generated
    by the Rust implementation to ensure byte-for-byte compatibility.
    """

    @pytest.fixture
    def test_vectors_path(self):
        """Path to test vectors JSON file."""
        path = Path(__file__).parents[1] / "fixtures" / "test_vectors.json"
        ensure_test_vectors(path)
        return path

    def _load_message_vectors(self, test_vectors_path):
        """Load message vectors from test vectors file, handling both old and new formats."""
        with open(test_vectors_path) as f:
            data = json.load(f)
        # New format: dict with "message_vectors" key
        if isinstance(data, dict) and "message_vectors" in data:
            return data["message_vectors"]
        # Old format: direct list of vectors
        return data

    def test_load_and_validate_vectors_decode(self, test_vectors_path):
        """Load test vectors and validate that Rust frames decode to expected payload values.

        Note: This tests semantic equality, not byte-for-byte encoding equality.
        CBOR libraries may use different key ordering (Rust uses alphabetical,
        Python uses insertion order), so re-encoding won't produce identical bytes.
        What matters is that both implementations decode to the same logical values.
        """
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_message_vectors(test_vectors_path)

        def normalize_payload(payload):
            """Normalize payload for comparison (handle $bytes encoding)."""
            if isinstance(payload, dict):
                if "$bytes" in payload:
                    return bytes.fromhex(payload["$bytes"])
                return {k: normalize_payload(v) for k, v in payload.items()}
            elif isinstance(payload, list):
                return [normalize_payload(v) for v in payload]
            return payload

        for vector in vectors:
            name = vector["name"]
            expected_payload = normalize_payload(vector["payload"])

            # Decode Rust-generated CBOR and compare values
            rust_cbor = bytes.fromhex(vector["cbor_hex"])
            decoded_payload = cbor2.loads(rust_cbor)

            # Compare key fields that should match
            # Note: CBOR omits keys with null values, but JSON includes them
            # Filter out null values from expected for comparison
            expected_keys = {k for k, v in expected_payload.items() if v is not None}
            assert decoded_payload.keys() == expected_keys, \
                f"Key mismatch for {name}: {decoded_payload.keys()} vs {expected_keys}"

    def test_rust_generated_frames_decodable(self, test_vectors_path):
        """Frames generated by Rust should be decodable by Python."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_message_vectors(test_vectors_path)

        for vector in vectors:
            name = vector["name"]

            if "profile1_hex" in vector:
                frame = bytes.fromhex(vector["profile1_hex"])
                decoded = Profile1Framer.decode(frame)
                assert decoded.message_type.value == vector["message_type"]

    def test_rust_signed_announce_verifiable(self, test_vectors_path):
        """Signed ANNOUNCE from Rust should be verifiable by Python."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.crypto import verify_signature
        from nacl.signing import VerifyKey

        def extract_pubkey_from_peer_id(peer_id: bytes) -> bytes:
            """Extract Ed25519 public key from libp2p PeerId format.

            libp2p PeerId for Ed25519 (38 bytes):
            - [0]: 0x00 (identity hash function)
            - [1]: 0x24 (length = 36)
            - [2:4]: 0x08 0x01 (protobuf field 1: key type = Ed25519)
            - [4:6]: 0x12 0x20 (protobuf field 2: data, 32 bytes)
            - [6:38]: 32-byte Ed25519 public key
            """
            if len(peer_id) != 38:
                raise ValueError(f"Invalid PeerId length: {len(peer_id)} (expected 38)")
            if peer_id[0:6] != bytes([0x00, 0x24, 0x08, 0x01, 0x12, 0x20]):
                raise ValueError("Invalid PeerId format (not Ed25519)")
            return peer_id[6:38]

        vectors = self._load_message_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "announce_signed":
                continue

            # Decode the CBOR payload
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            announce_dict = cbor2.loads(payload_bytes)

            # Extract node_id (libp2p PeerId) and signature
            # Note: CBOR may deserialize Vec<u8> as list, so convert to bytes
            node_id = announce_dict["node_id"]
            if isinstance(node_id, list):
                node_id = bytes(node_id)
            signature = announce_dict["signature"]
            if isinstance(signature, list):
                signature = bytes(signature)

            # Extract the 32-byte public key from 38-byte PeerId
            public_key = extract_pubkey_from_peer_id(node_id)

            # Create signable dict (without signature)
            signable_dict = {
                "node_id": node_id,
                "announce_seq": announce_dict["announce_seq"],
                "collections": announce_dict["collections"],
                "timestamp": announce_dict["timestamp"],
                "expires_at": announce_dict["expires_at"],
            }

            # Verify signature using Python crypto
            try:
                verify_key = VerifyKey(public_key)
                assert verify_signature(signable_dict, signature, verify_key), \
                    "Rust signature failed verification in Python"
            except Exception as e:
                pytest.fail(f"Signature verification failed: {e}")

    def test_manifest_schema_matches_python(self, test_vectors_path):
        """MANIFEST from Rust should have nested manifest object (not bytes)."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_message_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "manifest_response":
                continue

            # Decode the CBOR payload from Rust
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            manifest_msg = cbor2.loads(payload_bytes)

            # Verify manifest is a nested dict, not bytes
            assert isinstance(manifest_msg["manifest"], dict), \
                "Rust MANIFEST should contain nested manifest object, not bytes"

            # Verify key fields exist
            manifest = manifest_msg["manifest"]
            assert "protocol" in manifest
            assert "collection_id" in manifest
            assert "name" in manifest
            assert "torrent" in manifest

    def test_membership_messages_decodable(self, test_vectors_path):
        """Membership messages (INVITE, JOIN, JOIN_ACK, LEAVE, REVOKE) should decode correctly."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        membership_names = ["invite", "join", "join_ack", "leave", "revoke_unsigned", "revoke_signed"]

        vectors = self._load_message_vectors(test_vectors_path)

        found = 0
        for vector in vectors:
            if vector["name"] not in membership_names:
                continue

            found += 1
            name = vector["name"]

            # Decode the CBOR payload
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            msg_dict = cbor2.loads(payload_bytes)

            # Verify collection_id is a string (all membership messages have this)
            assert "collection_id" in msg_dict, f"{name}: missing collection_id"
            assert isinstance(msg_dict["collection_id"], str), f"{name}: collection_id should be string"

            # Verify specific fields based on message type
            if name == "invite":
                assert "invite_token" in msg_dict
                assert "expires_at" in msg_dict
                assert "inviter_id" in msg_dict
                assert "permissions" in msg_dict
            elif name == "join":
                assert "invite_token" in msg_dict
                assert "node_id" in msg_dict
                assert "timestamp" in msg_dict
            elif name == "join_ack":
                assert "node_id" in msg_dict
                assert "collection_key" in msg_dict
                assert "member_since" in msg_dict
                assert "permissions" in msg_dict
            elif name == "leave":
                assert "node_id" in msg_dict
            elif name.startswith("revoke"):
                assert "revoked_node_id" in msg_dict
                assert "admin_id" in msg_dict
                assert "timestamp" in msg_dict

        assert found == len(membership_names), f"Expected {len(membership_names)} membership vectors, found {found}"

    def test_rust_signed_revoke_verifiable(self, test_vectors_path):
        """Signed REVOKE from Rust should be verifiable by Python."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.crypto import verify_signature
        from nacl.signing import VerifyKey

        def extract_pubkey_from_peer_id(peer_id: bytes) -> bytes:
            """Extract Ed25519 public key from libp2p PeerId format."""
            if len(peer_id) != 38:
                raise ValueError(f"Invalid PeerId length: {len(peer_id)} (expected 38)")
            if peer_id[0:6] != bytes([0x00, 0x24, 0x08, 0x01, 0x12, 0x20]):
                raise ValueError("Invalid PeerId format (not Ed25519)")
            return peer_id[6:38]

        vectors = self._load_message_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "revoke_signed":
                continue

            # Decode the CBOR payload
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            revoke_dict = cbor2.loads(payload_bytes)

            # Extract admin_id (who signed) and signature
            admin_id = revoke_dict["admin_id"]
            if isinstance(admin_id, list):
                admin_id = bytes(admin_id)
            signature = revoke_dict["signature"]
            if isinstance(signature, list):
                signature = bytes(signature)

            # Extract the 32-byte public key from 38-byte PeerId
            public_key = extract_pubkey_from_peer_id(admin_id)

            # Get revoked_node_id as bytes
            revoked_node_id = revoke_dict["revoked_node_id"]
            if isinstance(revoked_node_id, list):
                revoked_node_id = bytes(revoked_node_id)

            # Create signable dict (without signature, with optional fields handled)
            signable_dict = {
                "collection_id": revoke_dict["collection_id"],
                "revoked_node_id": revoked_node_id,
                "admin_id": admin_id,
                "timestamp": revoke_dict["timestamp"],
            }
            # Add reason if present
            if "reason" in revoke_dict and revoke_dict["reason"] is not None:
                signable_dict["reason"] = revoke_dict["reason"]

            # Verify signature using Python crypto
            try:
                verify_key = VerifyKey(public_key)
                assert verify_signature(signable_dict, signature, verify_key), \
                    "Rust REVOKE signature failed verification in Python"
            except Exception as e:
                pytest.fail(f"REVOKE signature verification failed: {e}")

    def test_get_members_message_decodable(self, test_vectors_path):
        """GET_MEMBERS message should decode correctly (P2: Section 6.17)."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_message_vectors(test_vectors_path)

        found = False
        for vector in vectors:
            if vector["name"] != "get_members":
                continue

            found = True

            # Decode the CBOR payload
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            msg_dict = cbor2.loads(payload_bytes)

            # Verify required fields
            assert "collection_id" in msg_dict, "GET_MEMBERS: missing collection_id"
            assert isinstance(msg_dict["collection_id"], str), "GET_MEMBERS: collection_id should be string"
            assert "requester_id" in msg_dict, "GET_MEMBERS: missing requester_id"
            # requester_id should be bytes (CBOR byte string)
            requester_id = msg_dict["requester_id"]
            if isinstance(requester_id, list):
                requester_id = bytes(requester_id)
            assert isinstance(requester_id, bytes), "GET_MEMBERS: requester_id should be bytes"

            # Verify frames are decodable
            if "profile1_hex" in vector:
                frame = bytes.fromhex(vector["profile1_hex"])
                decoded = Profile1Framer.decode(frame)
                assert decoded.message_type.value == 0x0015  # GET_MEMBERS

        assert found, "GET_MEMBERS test vector not found"

    def test_members_message_decodable(self, test_vectors_path):
        """MEMBERS message should decode correctly (P2: Section 6.18)."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_message_vectors(test_vectors_path)

        members_vectors = ["members_with_members", "members_empty"]
        found = 0

        for vector in vectors:
            if vector["name"] not in members_vectors:
                continue

            found += 1
            name = vector["name"]

            # Decode the CBOR payload
            cbor_hex = vector["cbor_hex"]
            payload_bytes = bytes.fromhex(cbor_hex)
            msg_dict = cbor2.loads(payload_bytes)

            # Verify required fields
            assert "collection_id" in msg_dict, f"{name}: missing collection_id"
            assert isinstance(msg_dict["collection_id"], str), f"{name}: collection_id should be string"
            assert "members" in msg_dict, f"{name}: missing members"
            assert isinstance(msg_dict["members"], list), f"{name}: members should be list"
            assert "total_count" in msg_dict, f"{name}: missing total_count"
            assert isinstance(msg_dict["total_count"], int), f"{name}: total_count should be int"

            # Verify member entries have correct structure
            for i, member in enumerate(msg_dict["members"]):
                assert "node_id" in member, f"{name}[{i}]: missing node_id"
                assert "permissions" in member, f"{name}[{i}]: missing permissions"
                assert "joined_at" in member, f"{name}[{i}]: missing joined_at"
                assert "last_seen" in member, f"{name}[{i}]: missing last_seen"
                assert "status" in member, f"{name}[{i}]: missing status"

                # node_id should be bytes (CBOR byte string)
                node_id = member["node_id"]
                if isinstance(node_id, list):
                    node_id = bytes(node_id)
                assert isinstance(node_id, bytes), f"{name}[{i}]: node_id should be bytes"

            # Verify consistency of total_count
            if name == "members_empty":
                assert len(msg_dict["members"]) == 0, "members_empty should have no members"
                assert msg_dict["total_count"] == 0, "members_empty should have total_count=0"
            elif name == "members_with_members":
                assert len(msg_dict["members"]) > 0, "members_with_members should have members"
                assert msg_dict["total_count"] >= len(msg_dict["members"]), \
                    "total_count should be >= actual members"

            # Verify frames are decodable
            if "profile1_hex" in vector:
                frame = bytes.fromhex(vector["profile1_hex"])
                decoded = Profile1Framer.decode(frame)
                assert decoded.message_type.value == 0x0016  # MEMBERS

        assert found == len(members_vectors), f"Expected {len(members_vectors)} MEMBERS vectors, found {found}"


# =============================================================================
# Namespace Derivation Interop Tests
# =============================================================================

class TestNamespaceDerivationInterop:
    """
    Tests for namespace derivation consistency between implementations.

    Validates that DHT keys and pubsub topics are derived identically
    in both Rust and Python implementations.
    """

    @pytest.fixture
    def test_vectors_path(self):
        """Path to test vectors JSON file."""
        return Path(__file__).parents[1] / "fixtures" / "test_vectors.json"

    def _load_namespace_vectors(self, test_vectors_path):
        """Load namespace vectors from test vectors file."""
        with open(test_vectors_path) as f:
            data = json.load(f)
        if isinstance(data, dict) and "namespace_vectors" in data:
            return data["namespace_vectors"]
        return []

    def test_public_dht_key_matches_rust(self, test_vectors_path):
        """Python public DHT key derivation should match Rust."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.crypto import derive_dht_key

        vectors = self._load_namespace_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "public_dht_key":
                continue

            collection_id = vector["input"]
            expected_hex = vector["output"]

            # Derive using Python implementation
            result = derive_dht_key(collection_id)

            assert result.hex() == expected_hex, \
                f"Public DHT key mismatch for '{collection_id}': " \
                f"got {result.hex()}, expected {expected_hex}"

    def test_public_pubsub_topic_matches_rust(self, test_vectors_path):
        """Python public pubsub topic derivation should match Rust."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.dht import derive_pubsub_topic

        vectors = self._load_namespace_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "public_pubsub_topic":
                continue

            collection_id = vector["input"]
            expected_topic = vector["output"]

            # Derive using Python implementation
            result = derive_pubsub_topic(collection_id)

            assert result == expected_topic, \
                f"Public pubsub topic mismatch for '{collection_id}': " \
                f"got {result}, expected {expected_topic}"

    def test_private_dht_key_matches_rust(self, test_vectors_path):
        """Python private DHT key derivation should match Rust."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.crypto import derive_private_dht_key

        vectors = self._load_namespace_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "private_dht_key":
                continue

            # Private key input is hex-encoded
            input_hex = vector["input_hex"]
            collection_key = bytes.fromhex(input_hex)
            expected_hex = vector["output"]

            # Derive using Python implementation
            result = derive_private_dht_key(collection_key)

            assert result.hex() == expected_hex, \
                f"Private DHT key mismatch: got {result.hex()}, expected {expected_hex}"

    def test_private_pubsub_topic_matches_rust(self, test_vectors_path):
        """Python private pubsub topic derivation should match Rust."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        from dcpp_python.dht import derive_private_pubsub_topic

        vectors = self._load_namespace_vectors(test_vectors_path)

        for vector in vectors:
            if vector["name"] != "private_pubsub_topic":
                continue

            # Private key input is hex-encoded
            input_hex = vector["input_hex"]
            collection_key = bytes.fromhex(input_hex)
            expected_topic = vector["output"]

            # Derive using Python implementation
            result = derive_private_pubsub_topic(collection_key)

            assert result == expected_topic, \
                f"Private pubsub topic mismatch: got {result}, expected {expected_topic}"

    def test_all_namespace_vectors_present(self, test_vectors_path):
        """Verify all expected namespace vectors are present."""
        if not test_vectors_path.exists():
            pytest.skip(f"Test vectors file not found: {test_vectors_path}")

        vectors = self._load_namespace_vectors(test_vectors_path)

        expected_names = {
            "public_dht_key",
            "public_pubsub_topic",
            "private_dht_key",
            "private_pubsub_topic",
        }

        actual_names = {v["name"] for v in vectors}

        missing = expected_names - actual_names
        assert not missing, f"Missing namespace vectors: {missing}"


# =============================================================================
# Protocol Compliance Tests
# =============================================================================

class TestRFCCompliance:
    """Test compliance with DCPP RFC requirements."""

    def test_max_message_size_enforced(self):
        """Messages exceeding 32MB should be rejected (RFC Section 5.5)."""
        from dcpp_python.framing import MessageTooLargeError

        # Just over 32MB
        large_payload = b"x" * (MAX_MESSAGE_SIZE + 1)

        with pytest.raises(MessageTooLargeError):
            Profile1Framer.encode(MessageType.MANIFEST, large_payload)

        with pytest.raises(MessageTooLargeError):
            Profile1Framer.encode(MessageType.MANIFEST, large_payload)

    def test_challenge_length_max(self):
        """Challenge length should be clamped to 1024 (RFC Section 6.8)."""
        challenge = Challenge(cid="QmTest", offset=0, length=2048)

        # Length is clamped on construction for safety
        assert challenge.length == 1024  # Clamped to MAX_LENGTH

        # And serialization also uses clamped value
        challenge_dict = challenge.to_dict()
        assert challenge_dict["length"] == 1024

    def test_challenge_validated_construction(self):
        """Challenge.new_validated should validate against item size."""
        # Valid: offset + clamped_length <= item_size
        challenge = Challenge.new_validated("QmTest", offset=500, length=2000, item_size=2000)
        assert challenge.length == 1024  # Clamped
        assert challenge.offset == 500

        # Invalid: offset + clamped_length > item_size
        with pytest.raises(ValueError, match="Invalid offset"):
            Challenge.new_validated("QmTest", offset=500, length=1000, item_size=1000)

    def test_announce_rate_limit_fields(self):
        """ANNOUNCE should include all required replay protection fields."""
        collections = [CollectionAnnouncement(
            id="eth:0x1234",
            manifest_cid="QmTest",
            coverage=1.0,
        )]

        timestamp = int(time.time())
        announce = Announce(
            node_id=b"\x01\x02\x03\x04",
            announce_seq=timestamp,
            collections=collections,
            timestamp=timestamp,
            expires_at=timestamp + 3600,
            signature=b"\x00" * 64,
        )

        announce_dict = announce.to_dict()

        # RFC Section 6.3.1 - Required fields for replay protection
        assert "announce_seq" in announce_dict
        assert "timestamp" in announce_dict
        assert "expires_at" in announce_dict
        assert "signature" in announce_dict

    def test_profile1_header_size_20_bytes(self):
        """Profile 1 header should be 20 bytes (RFC Section 5.1).

        Header format: Magic(4) + Version(2) + Type(2) + RequestID(4) + Length(4) + CRC32(4) = 20
        """
        payload = b"test"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        # Total frame = header + payload
        assert len(frame) == 20 + len(payload)


# =============================================================================
# Edge Cases and Error Handling
# =============================================================================

class TestEdgeCases:
    """Test edge cases and error handling."""

    def test_unknown_message_type(self):
        """Unknown message types should raise an error."""
        # Manually construct a Profile 1 frame with invalid message type
        bad_type = 0xFFFF  # Reserved
        payload = b"\xa0"
        request_id = 0
        length = len(payload)
        crc = crc32c(payload)

        frame = (
            MAGIC_BYTES
            + struct.pack(">H", 0x0100)  # version
            + struct.pack(">H", bad_type)
            + struct.pack(">I", request_id)
            + struct.pack(">I", length)
            + struct.pack(">I", crc)
            + payload
        )

        with pytest.raises((ValueError, KeyError, FramingError)):
            Profile1Framer.decode(frame)

    def test_truncated_frame(self):
        """Truncated frames should be detected."""
        payload = b"test payload"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        # Truncate the frame
        truncated = frame[:-5]

        with pytest.raises(FramingError):
            Profile1Framer.decode(truncated)

    def test_truncated_frame_profile1(self):
        """Truncated Profile 1 frames should be detected."""
        payload = b"test payload"
        frame = Profile1Framer.encode(MessageType.HELLO, payload)

        # Truncate the frame
        truncated = frame[:-5]

        with pytest.raises(FramingError):
            Profile1Framer.decode(truncated)

    def test_invalid_magic_profile1(self):
        """Invalid magic bytes should be rejected."""
        from dcpp_python.framing import MagicBytesError

        # Frame with wrong magic (20-byte header total)
        bad_frame = b"NOPE" + b"\x00" * 16 + b"\xa0"

        with pytest.raises(MagicBytesError):
            Profile1Framer.decode(bad_frame)

    def test_empty_collections_list(self):
        """Empty collections lists should be handled correctly."""
        hello = Hello(
            version="1.0.0",
            node_id=b"\x01\x02\x03\x04",
            capabilities=[],
            collections=[],
            timestamp=1000,
        )

        cbor_bytes = hello.to_cbor()
        restored = Hello.from_cbor(cbor_bytes)

        assert restored.collections == []
        assert restored.capabilities == []

    def test_unicode_in_strings(self):
        """Unicode strings should be handled correctly."""
        manifest = Manifest(
            protocol="dcpp/1.0",
            type=CollectionType.PHOTO_LIBRARY,
            access_mode=AccessMode.PRIVATE,
            collection_id="private:test",
            name="Family Photos \U0001F4F7",  # Camera emoji
            version=1,
            created_at=1000,
            updated_at=1000,
            total_items=0,
            total_size_bytes=0,
            merkle_root="QmTest",
            torrent=TorrentInfo(
                infohash="abc123",
                magnet="magnet:?xt=urn:btih:abc123",
                piece_length=262144,
            ),
        )

        cbor_bytes = manifest.to_cbor()
        restored = Manifest.from_cbor(cbor_bytes)

        assert restored.name == "Family Photos \U0001F4F7"

    def test_large_node_id(self):
        """Large node IDs should be handled (up to 64 bytes typical)."""
        # Ed25519 public key is 32 bytes, but node_id could be larger
        large_node_id = b"\x01" * 64

        hello = Hello(
            version="1.0.0",
            node_id=large_node_id,
            capabilities=[],
            collections=[],
            timestamp=1000,
        )

        cbor_bytes = hello.to_cbor()
        restored = Hello.from_cbor(cbor_bytes)

        assert restored.node_id == large_node_id


# =============================================================================
# Signature Compatibility Tests
# =============================================================================

class TestSignatureInterop:
    """Test Ed25519 signature compatibility."""

    def test_signature_format(self):
        """Signatures should be 64 bytes (Ed25519)."""
        from dcpp_python.crypto import generate_keypair, sign_message

        signing_key, _ = generate_keypair()

        message = {"test": "data"}
        signature = sign_message(message, signing_key)

        assert len(signature) == 64

    def test_signature_verification(self):
        """Signatures should verify correctly."""
        from dcpp_python.crypto import generate_keypair, sign_message, verify_signature

        signing_key, verify_key = generate_keypair()

        message = {"collection_id": "eth:0x1234", "timestamp": 1000}
        signature = sign_message(message, signing_key)

        assert verify_signature(message, signature, verify_key)

    def test_signature_over_canonical_cbor(self):
        """Signatures should be computed over canonical CBOR bytes."""
        from dcpp_python.crypto import generate_keypair, sign_message

        signing_key, _ = generate_keypair()

        # Same logical data, different Python dict orderings
        # Both should produce the same CBOR (assuming canonical encoding)
        msg1 = {"a": 1, "b": 2, "c": 3}
        msg2 = {"c": 3, "a": 1, "b": 2}

        sig1 = sign_message(msg1, signing_key)
        sig2 = sign_message(msg2, signing_key)

        # Note: This test assumes the sign_message function uses
        # canonical CBOR. If not, signatures will differ.
        # This is a known interoperability concern.


# =============================================================================
# Test Vector Generation Helper
# =============================================================================

def generate_test_vectors_json() -> str:
    """
    Generate test vectors as JSON for cross-implementation testing.

    This function creates a JSON file with known-good message bytes
    that can be used to validate other implementations.
    """
    vectors = []

    for tv in TEST_VECTORS:
        payload = cbor2.dumps(tv.payload_dict)
        p1_frame = Profile1Framer.encode(tv.message_type, payload)

        vectors.append({
            "name": tv.name,
            "message_type": tv.message_type.value,
            "payload": tv.payload_dict,
            "cbor_hex": payload.hex(),
            "profile1_hex": p1_frame.hex(),
        })

    return json.dumps(vectors, indent=2, default=_json_serializer)


def _json_serializer(obj):
    """JSON serializer for bytes objects."""
    if isinstance(obj, bytes):
        return {"$bytes": obj.hex()}
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")


if __name__ == "__main__":
    # Generate test vectors when run directly
    print(generate_test_vectors_json())
