"""
DCPP - Distributed Content Preservation Protocol

Python implementation of the DCPP/1.0 Wire Protocol.
"""

from .core.constants import (
    PROTOCOL_ID,
    PROTOCOL_VERSION,
    MAGIC_BYTES,
    MAX_MESSAGE_SIZE,
    MessageType,
    ErrorCode,
    Capability,
    StorageType,
    ItemStatus,
    CollectionType,
    AccessMode,
    GoodbyeReason,
    MemberStatus,
    Permission,
    KeyRotationReason,
    NodeState,
    CollectionState,
    PeerLimits,
    RetryConfig,
    ConnectionHealth,
    CONFORMANCE_DEFAULTS,
    # Registry fallback helpers
    goodbye_reason_fallback,
    member_status_fallback,
    permission_fallback,
    item_status_fallback,
    storage_type_for_retrieval,
    collection_type_fallback,
    validate_access_mode,
    key_rotation_reason_fallback,
    filter_capabilities,
)
from .core.framing import Profile1Framer
from .core.messages import (
    Hello,
    Announce,
    CollectionAnnouncement,
    GetManifest,
    ManifestResponse,
    GetPeers,
    PeersResponse,
    PeerInfo,
    HealthProbe,
    Challenge,
    HealthResponse,
    ChallengeResponse,
    Goodbye,
    ErrorResponse,
    Invite,
    Join,
    JoinAck,
    Leave,
    Revoke,
    GetMembers,
    MembersResponse,
    MemberInfo,
)
from .manifest.manifest import (
    Manifest,
    Item,
    TorrentInfo,
    ShardingConfig,
    SourceInfo,
    EncryptionConfig,
    SubCollection,
    MediaFile,
    FileMetadata,
    ShardManifest,
)
from .storage.base import StorageBackend, StorageStats
from .storage.filesystem import FileSystemStorage
from .storage.memory import MemoryStorage
from .storage.genesis import (
    GenesisState,
    GenesisRecord,
    GenesisStore,
    FileSystemGenesisStore,
    MemoryGenesisStore,
)
from .storage.interfaces import StorageBackendProtocol
from .crypto.cid import (
    parse_cid,
    verify_cid,
    compute_cid,
    compute_multihash,
    cid_to_bytes,
    bytes_to_cid,
    CidInfo,
    Multicodec,
    Multihash,
)
from .network.dht.base import (
    DHTBackend,
    DHTConfig,
    ProviderRecord,
    CollectionDiscovery,
    LocalDHT,
    SimulatedNetworkDHT,
    derive_pubsub_topic,
    derive_private_pubsub_topic,
)
from .network.dht.kademlia import (
    KademliaDHT,
    DHTCommand,
    DHTCommandType,
    DHTResponse,
    BootstrapConfig,
    derive_dht_key as derive_dht_key_real,
    derive_private_dht_key as derive_private_dht_key_real,
)
from .network.libp2p.simulated import (
    Host,
    HostConfig,
    PeerIdentity,
    Stream,
    StreamState,
    StreamInfo,
    SimulatedHost,
    DCPPProtocolHandler,
    DCPPNode,
)
from .network.libp2p.real import (
    DCPP_PROTOCOL_ID,
    HostEvent,
    HostEventData,
    DCPPRequest,
    DCPPResponse,
    RealHostConfig,
    RealHost,
    DCPPRealNode,
    is_available as libp2p_is_available,
)
from .network.bittorrent.base import (
    TorrentStatus,
    TorrentStats,
    Piece,
    TorrentFile,
    TorrentMetadata,
    BitTorrentBackend,
    MockBitTorrentBackend,
    DCPPTorrentManager,
    MIN_PIECE_SIZE,
    MAX_PIECE_SIZE,
    recommended_piece_length,
)
from .network.bittorrent.real import (
    RealBitTorrentBackend,
    HybridTorrentMetadata,
    PieceMapping,
    recommended_piece_length_bep52,
    get_backend as get_bittorrent_backend,
)
from .core.validation import (
    MessageValidator,
    ValidationResult,
    ValidationStatus,
    PendingRequest,
    is_known_capability,
    parse_capabilities,
)
from .crypto.signing import (
    sign_announce,
    verify_announce,
    verify_announce_from_peer_id,
    pubkey_from_peer_id,
    ed25519_pubkey_to_peer_id,
    derive_peer_id,
    generate_keypair,
)

__version__ = "0.1.0"
__all__ = [
    # Constants
    "PROTOCOL_ID",
    "PROTOCOL_VERSION",
    "MAGIC_BYTES",
    "MAX_MESSAGE_SIZE",
    "MessageType",
    "ErrorCode",
    "Capability",
    "StorageType",
    "ItemStatus",
    "CollectionType",
    "AccessMode",
    "GoodbyeReason",
    "MemberStatus",
    "Permission",
    "KeyRotationReason",
    "NodeState",
    "CollectionState",
    "PeerLimits",
    "RetryConfig",
    "ConnectionHealth",
    "CONFORMANCE_DEFAULTS",
    # Registry fallback helpers
    "goodbye_reason_fallback",
    "member_status_fallback",
    "permission_fallback",
    "item_status_fallback",
    "storage_type_for_retrieval",
    "collection_type_fallback",
    "validate_access_mode",
    "key_rotation_reason_fallback",
    "filter_capabilities",
    # Framing
    "Profile1Framer",
    # Messages
    "Hello",
    "Announce",
    "CollectionAnnouncement",
    "GetManifest",
    "ManifestResponse",
    "GetPeers",
    "PeersResponse",
    "PeerInfo",
    "HealthProbe",
    "Challenge",
    "HealthResponse",
    "ChallengeResponse",
    "Goodbye",
    "ErrorResponse",
    "Invite",
    "Join",
    "JoinAck",
    "Leave",
    "Revoke",
    "GetMembers",
    "MembersResponse",
    "MemberInfo",
    # Manifest
    "Manifest",
    "Item",
    "TorrentInfo",
    "ShardingConfig",
    "SourceInfo",
    "EncryptionConfig",
    "SubCollection",
    "MediaFile",
    "FileMetadata",
    "ShardManifest",
    # Storage
    "StorageBackend",
    "StorageBackendProtocol",
    "FileSystemStorage",
    "MemoryStorage",
    "StorageStats",
    "GenesisState",
    "GenesisRecord",
    "GenesisStore",
    "FileSystemGenesisStore",
    "MemoryGenesisStore",
    # CID Verification
    "parse_cid",
    "verify_cid",
    "compute_cid",
    "compute_multihash",
    "cid_to_bytes",
    "bytes_to_cid",
    "CidInfo",
    "Multicodec",
    "Multihash",
    # DHT
    "DHTBackend",
    "DHTConfig",
    "ProviderRecord",
    "CollectionDiscovery",
    "LocalDHT",
    "SimulatedNetworkDHT",
    "derive_pubsub_topic",
    "derive_private_pubsub_topic",
    # DHT Real (Kademlia)
    "KademliaDHT",
    "DHTCommand",
    "DHTCommandType",
    "DHTResponse",
    "BootstrapConfig",
    "derive_dht_key_real",
    "derive_private_dht_key_real",
    # libp2p
    "Host",
    "HostConfig",
    "PeerIdentity",
    "Stream",
    "StreamState",
    "StreamInfo",
    "SimulatedHost",
    "DCPPProtocolHandler",
    "DCPPNode",
    # libp2p_real
    "DCPP_PROTOCOL_ID",
    "HostEvent",
    "HostEventData",
    "DCPPRequest",
    "DCPPResponse",
    "RealHostConfig",
    "RealHost",
    "DCPPRealNode",
    "libp2p_is_available",
    # BitTorrent
    "TorrentStatus",
    "TorrentStats",
    "Piece",
    "TorrentFile",
    "TorrentMetadata",
    "BitTorrentBackend",
    "MockBitTorrentBackend",
    "DCPPTorrentManager",
    "MIN_PIECE_SIZE",
    "MAX_PIECE_SIZE",
    "recommended_piece_length",
    # BitTorrent Real
    "RealBitTorrentBackend",
    "HybridTorrentMetadata",
    "PieceMapping",
    "recommended_piece_length_bep52",
    "get_bittorrent_backend",
    # Validation
    "MessageValidator",
    "ValidationResult",
    "ValidationStatus",
    "PendingRequest",
    "is_known_capability",
    "parse_capabilities",
    # Crypto / Signing
    "sign_announce",
    "verify_announce",
    "verify_announce_from_peer_id",
    "pubkey_from_peer_id",
    "ed25519_pubkey_to_peer_id",
    "derive_peer_id",
    "generate_keypair",
]
